name: CI

on:
  push:
    branches:
      - master
  

jobs:
  build:
    runs-on: nawaz

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Type name
      run: echo "Hi Nawaz"
      
   
   
    
